# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(705, 679)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 90, 691, 571))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.black_white = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.black_white.setObjectName("black_white")
        self.gridLayout.addWidget(self.black_white, 2, 1, 1, 1)
        self.pierogi = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.pierogi.setObjectName("pierogi")
        self.gridLayout.addWidget(self.pierogi, 1, 0, 1, 1)
        self.schabowy = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.schabowy.setObjectName("schabowy")
        self.gridLayout.addWidget(self.schabowy, 2, 0, 1, 1)
        self.rosol = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.rosol.setObjectName("rosol")
        self.gridLayout.addWidget(self.rosol, 0, 0, 1, 1)
        self.image = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.image.setText("")
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 3, 0, 1, 2)
        self.Menu = QtWidgets.QLabel(parent=Dialog)
        self.Menu.setGeometry(QtCore.QRect(10, 30, 689, 50))
        self.Menu.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Menu.setFont(font)
        self.Menu.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Menu.setObjectName("Menu")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.black_white.setText(_translate("Dialog", "Czarno-białe"))
        self.pierogi.setText(_translate("Dialog", "Pierogi ruskie"))
        self.schabowy.setText(_translate("Dialog", "Schabowy"))
        self.rosol.setText(_translate("Dialog", "Rosół"))
        self.Menu.setText(_translate("Dialog", "Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
